### PR TITLE
Details on new pages

### PR DESCRIPTION
**Pull request by Jay-o-Way**
## Description

Few small things

## Motivation and Context

...that weren't perfect

I would also suggest this icon (yay or nay?)
image

## Screenshots (if appropriate):

(before)
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
@karkarl?

**Review by niels9001 — CHANGES_REQUESTED** [review]
image

The titles + values no longer align horizontally?

**Comment by Jay-o-Way** [comment]
Woops. Will do.

**Comment by Jay-o-Way** [comment]
Fixed! :)
Thoughts on the icon?

**Review by niels9001 — APPROVED** [review]

**Comment by Jay-o-Way** [comment]
@niels9001 Thoughts on the icon? (it's not included - yet)

**Comment by niels9001** [comment]
> @niels9001 Thoughts on the icon? (it's not included - yet)

If it works on W10/MDL2, please go ahead!

**Comment by Jay-o-Way** [comment]
> If it works on W10/MDL2,

Good point 👍🏻 It's available in MDL2, but it looks a bit different...
image

**Pull request merged**
