### PR TITLE
Searching icons by tags

### LINKED ISSUE #1544: Add searchable tags to Icons
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Description

In the **Icons** page, you can search by `Name` and `Unitcode point`. It'd be easier to find icons if they had tags that represent the symbol or its meaning.

For example, the `Color` icon, which is a palette, could also be able to be found with [palette] or [theme].

### Screenshots

_No response_

### Windows version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
## Description

Closes #1544.
This PR will enable searching icons based on tags on the Iconography page. Icon tags are assigned on the IconsData.json file.

## Motivation and Context

The current icon searching is based only on the icon name or its code. Some icon's names are not very intuitive, or some icons can represent several things. So, to get an icon code and if you don't know the icon name, you need to search it manually by scrolling through more than 1400 icons.

## How Has This Been Tested?

Tested on the VS.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by AndrewKeepCoding** [comment]
I added tags to 400 icons and didn't (couldn't) add tags to all >1400 icons. It takes too much time and patience. 😅
I'm expecting the tagging to be improved little by little.

**Comment by niels9001** [comment]
🔥🔥🔥

**Review by karkarl — APPROVED** [review]

**Comment by ghost1372** [comment]
Tnx @AndrewKeepCoding for this great pr.
for adding tags you dont need to write them by yourself, in this case we can use ChatGPT :)
as you can see, chatgtp generated 3 tags for each item.

image

**Pull request merged**
