### PR TITLE
Improve Color page sample code

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
## Description

Added sample code for the theme resource brush use.

## How Has This Been Tested?

Ran the app and confirme the change.

## Screenshots (if appropriate):
Before:
image

After:
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by niels9001** [comment]
Could we do just the XAML string as a code block and not the `Expander`? The core functionality of this tool is to quickly look up brushes, having the expander here would introduce additional scrolling and pushes down the most important info.. thoughts?

**Comment by AndrewKeepCoding** [comment]
Something like this?

image

**Comment by niels9001** [comment]
Nit: can we shorten the 'Text="..."' and keep everything on a single line?

**Comment by AndrewKeepCoding** [comment]
> Nit: can we shorten the 'Text="..."' and keep everything on a single line?

Pushed the changes.
image

**Pull request merged**
