### PR TITLE
Show item base classes

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
## Description

Shows the base classes of each control/element.

## Motivation and Context

This will help devs understand the inheritance structure of WinUI controls/elements.

## How Has This Been Tested?

Tested on VS.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by karkarl** [comment]
Thanks for the PR, this is an awesome addition! 

I think the breadcrumb bar should be below the header, since it's not for navigating and purely for informative purposes. @niels9001

**Comment by niels9001** [comment]
Oooh I like this.. agree with @karkarl that having it below the title makes more sense.

That being said, I think the page header is starting to become pretty info heavy.

image

I wonder if the inheritance and namespace should live under a button+flyout? It's relevant information, but also not critical information. Thoughts @AndrewKeepCoding @karkarl ?

**Comment by AndrewKeepCoding** [comment]
Changed the order and here is how it looks:
image

**Comment by AndrewKeepCoding** [comment]
> I wonder if the inheritance and namespace should live under a button+flyout? It's relevant information, but also not critical information. 

@niels9001 I agree. There's a lot of text around there. But IMHO, I thought it'd be better for devs, especially the new ones in WinUI, that this inheritance info just gets into their eyes.

**Comment by marcelwgn** [comment]
> > I wonder if the inheritance and namespace should live under a button+flyout? It's relevant information, but also not critical information.
> 
> @niels9001 I agree. There's a lot of text around there. But IMHO, I thought it'd be better for devs, especially the new ones in WinUI, that this inheritance info just gets into their eyes.

I might be an outlier with this position, but I don't think new devs really need to have that information often. There are very few situations where one wouldn't derive from UserControl/Control (which the new control templates already do). Out of curiosity, in which situation would this information would have been helpful to you @AndrewKeepCoding? 😃

**Comment by AndrewKeepCoding** [comment]
> Out of curiosity, in which situation would this information would have been helpful to you @AndrewKeepCoding? 😃

@marcelwgn
Now that I've been working with WinUI for a couple of years, I don't find this feature that helpful. But when I started working with WinUI 3, I remember that learning the inheritance of the elements helped me understand the framework better.

Might sound stupid and maybe it's just me, but for example, I remember I was assuming that `RichTextBox`, `AutoSuggestBox` and `NumberBox` derive from `TextBox`. 😅 After I learned that they are totally different controls, I tend to check out the inheritance of controls/elements when I use them by going all the way to the docs.

That's why I thought this feature would be good for devs new to WinUI. 

I totally understand your opinions guys. Let me know if you want to close this or modify it to a less texty way. 🙂

**Comment by karkarl** [comment]
Perhaps it can mirror the msdn format, and be placed under the control description? 

image

**Comment by AndrewKeepCoding** [comment]
It's didn't push the commit yet but looks like this:

image

**Comment by karkarl** [comment]
I think that looks great! Can you push the commit?

**Comment by AndrewKeepCoding** [comment]
@karkarl Done.

**Review by karkarl — APPROVED** [review]

**Pull request merged**
