### PR TITLE
Merge Feature/winappsdk 1.2 into main

### PR DESCRIPTION
**Pull request by bpulliam**
## Description
This merges the feature branch that has captured the road to 1.2 release.
Now that 1.2 stable has been released, we can bring this into main.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by gregwoo-microsoft — APPROVED** [review]
Works great! The only thing that I would change is adding the MediaPlayerElement control to the "recently added samples" list.

**Comment by gregwoo-microsoft** [comment]
In fact, here is the list of all of the controls that were updated since the last update:
AnimatedIcon
AutoSuggestBox
Button
CheckBox
ListView
RevealFocus
ScrollViewer
Slider
SplitButton
SplitView
Swipe
TitleBar
WebView2
SystemBackdrops

**Review by chingucoding — COMMENTED** [review]
What's up with the files in the `Helpers\Colorcode.internal` folder? Visual Studio does not seem to show them and they don't seem to be referenced (unless I'm missing something here).

**Comment by bpulliam** [comment]
> What's up with the files in the `Helpers\Colorcode.internal` folder? Visual Studio does not seem to show them and they don't seem to be referenced (unless I'm missing something here).

Colorcode.WinUI is built against the shipping version of WinUI and causes conflicts when WinUI Gallery is built against internal builds of WinUI. One of the tasks we have been working on is eliminating copies of the Gallery code and the cost of keeping them in sync. As such, we use the public WinUIGallery code to validate and develop WinUI itself. The Colorcode.Internal allows us to use Colorcode.Core directly when building WinUI Gallery internally, but it is not used in external builds. The switch is in the csproj file by changing the reference and using compile removes.

**Comment by chingucoding** [comment]
Ah I see, thanks for the clarification @bpulliam!

**Pull request merged**
