### PR TITLE
Fix: `Color > HighContrast` theme toggle highlight

### LINKED ISSUE #1671: `Color > Hight Contrast`: Incorrect Highlighting on Theme Toggle
### Which version of the app?

WinUI 3 Gallery

### Steps to Reproduce:
1. Navigate to the "Color > Hight Contrast".
2. Toggle the theme using the theme switch button at the top right corner.
3. Observe the changes in the text highlighting.

### Screenshots
 **Before Toggling the theme**
Image

**After Toggling the theme**
Image

### Expected Behavior:
The text should maintain consistent highlighting and text visibility regardless of the theme, with proper contrast between the background and text.

### Actual Behavior:
After toggling the theme, the text become poorly highlighted, making it less readable and causing visual inconsistency.

### PR DESCRIPTION
**Pull request by Zakariathr22**
## Description
The changes in this PR prevent the `SampleThemeListener` from applying theme changes to all child elements, including some textboxes, which do not need to be affected by the theme toggle. These changes address the issue of inconsistent text highlighting in the "High Contrast" section of the `ColorPage` by improving theme handling. The main changes are:
- Removed `<SampleThemeListener>` from `ColorPage`.
- Added `<SampleThemeListener>` to other "Color Sections" pages as needed for better modularity.

## Motivation and Context
Fixes #1671 

## How Has This Been Tested?
**Manually Tested** by toggling the theme in all sections of the `ColorPage` and observing the behavior.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Zakariathr22** [comment]
It appears that the wrapping element was interpreted as changes to all the lines 🤔.
The actual changes are `-3` `+24`.

**Comment by Jay-o-Way** [comment]
> t appears that the wrapping of elements was interpreted as changes to all the lines

Indentation changed, so technically all those lines are indeed different.

**Comment by Jay-o-Way** [comment]
Makes me think: If the `ColorPageExample` is supposed to change theme when the main app window does not, wouldn't it make more sense to build that ThemeListener into the ColorPageExample code once, and leave out all the rest?? @marcelwgn @niels9001

**Comment by Zakariathr22** [comment]
> Makes me think: If the `ColorPageExample` is supposed to change theme when the main app window does not, wouldn't it make more sense to build that ThemeListener into the ColorPageExample code once, and leave out all the rest?? @marcelwgn @niels9001 

I attempted this approach, but it didn't work as expected for a reason I couldn't identify.

**Review by niels9001 — APPROVED** [review]
Tested, works as expected! Thanks @zakariathr22!

**Comment by niels9001** [comment]
@zakariathr22 Just a small conflict, other than that we are good to go :-)!

**Comment by Zakariathr22** [comment]
@niels9001 any other suggestions?

@Jay-o-Way, your suggestions and adjustments are always appreciated!

**Comment by Zakariathr22** [comment]
@niels9001
Can I close this PR and create a new one since the changes are minimal, and starting fresh might be quicker and cleaner?

**Comment by Zakariathr22** [comment]
@niels9001 
Should I close this PR and create a new one since the changes are minimal, and starting fresh might be quicker and cleaner than resolving this conflict?

**Comment by niels9001** [comment]
> @niels9001 
> Should I close this PR and create a new one since the changes are minimal, and starting fresh will be quicker and cleaner than resolving these conflicts?

Sure, it that's easier thrn go for it! Whatever works best for you!

**Comment by Zakariathr22** [comment]
@niels9001 
I think the changes in #1680 can be merged without any conflicts.

**Comment by Jay-o-Way** [comment]
Yes, lots of PRs are being merged now, so a good time to update your repo and _main_ branch.

**Pull request closed without merging**
