### PR TITLE
add 23H2 and 24H2 in forms

### PR DESCRIPTION
**Pull request by Jay-o-Way**
## Description
(same as title)

## Motivation and Context
(no explanation needed)

## How Has This Been Tested?
(I dunno)

## Screenshots (if appropriate):
(nope)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] GitHub improvement

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
Does it make sense to add **24H2 (26052)** already? I bet a lot of devs are already working with it.

**Review by marcelwgn — APPROVED** [review]

**Comment by Jay-o-Way** [comment]
So... what's up?

**Comment by karkarl** [comment]
> Shall we add **24H2 (26052)** already? I bet a lot of devs are already working with it.

Sounds like a great idea!

**Pull request merged**
