### PR TITLE
Fix settings page crash on Windows 10

### LINKED ISSUE #1477: WinUI Gallery sample crashes when clicking Settings
### Which version of the app?

WinUI 3 Gallery

### Description

Start the sample, click the Settings link, app crashes (two independent repros).

### Screenshots

_No response_

### Windows version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HO-COOH**
## Description
On Windows 10, it does not seem to load `Microsoft.WindowsAppRuntime.Insights.Resource.dll` and this crash the app. Added a fallback for this.

## Motivation and Context
Closes #1477 

## How Has This Been Tested?
Manual

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by karkarl — APPROVED** [review]

**Comment by karkarl** [comment]
@HO-COOH do you mind resolving the conflict?

**Comment by HO-COOH** [comment]
> @HO-COOH do you mind resolving the conflict?

Done. I don't know how the conflict occurred tho.

**Comment by Scottj1s** [comment]
@HO-COOH thanks for this! I'll do some investigating on why the given assembly is not being found.  But we'll take this fix in the meantime.

**Pull request merged**
