### PR TITLE
Remove WindowHelper from FilePicker sample code

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
## Description
Removed the WinUI3Helper class from the `FilePicker` sample code and showed how to get the `MainWindow` from the `App` class instead.

## Motivation and Context
The sample code for the `FilePicker` controls uses the WindowHelper class which is implemented as a helper class in this project. This is very confusing because it looks like the WindowHelper class belongs to WinUI 3 and when one tries to use that code in their apps it just doesn't work. I find several questions in StackOverflow related to this and I think it's better not to use the WindowHelper in sample code.

## How Has This Been Tested?
Run the app and confirmed its content.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by AndrewKeepCoding** [comment]
@microsoft-github-policy-service agree

**Review by karkarl — COMMENTED** [review]
Thanks for the fix!

**Review by karkarl — APPROVED** [review]

**Comment by MartinZikmund** [comment]
@AndrewKeepCoding shouldn't the code snippets say App.MainWindow instead 👀?

**Comment by AndrewKeepCoding** [comment]
@MartinZikmund Thanks for pointing that out. 😵

**Pull request merged**
