### PR TITLE
fix incorrect links

### LINKED ISSUE #1232: Link to source code is broken for all items under Design guidance section.
### Which version of the app?

WinUI 3 Gallery

### Description

Link to source code is broken for all items under Design guidance section.

clicking on the button navigates to
https://github.com/microsoft/WinUI-Gallery/tree/main/WinUIGallery/ControlPages/[page].xaml
instead of 
https://github.com/microsoft/WinUI-Gallery/tree/main/WinUIGallery/ControlPages/DesignGuidance/[page].xaml

### Screenshots

_No response_

### Windows version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by insomniachi**
## Description
add **Folder** property ControlInfoDataGroup
if present it will be appended to base URL when navigating to source code for all child items.

## Motivation and Context
fixes #1232

## How Has This Been Tested?
Manual

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by insomniachi** [comment]
@microsoft-github-policy-service agree

**Comment by niels9001** [comment]
@insomniachi Should we update the .json file as well? Clicking on Colors => Source => XAML still goes to an incorrect URL?

**Comment by insomniachi** [comment]
@niels9001 .json is updated, folder name is added for the group Design guidance.
everything under the group (Typography,Colors,Icons,Accessibility) points to the right url

**Review by chingucoding — APPROVED** [review]
Awesome, thank you for fixing this!

**Comment by chingucoding** [comment]
@niels9001 If I click on the xaml link for the colors page, it seems to resolve correctly. Is it still broken for you?

**Comment by karenbtlai** [comment]
> @niels9001 If I click on the xaml link for the colors page, it seems to resolve correctly. Is it still broken for you?

Manually verified. Thanks for the fix @insomniachi :)

**Pull request merged**
