### PR TITLE
Update to WinAppSDK 1.5 and .NET8; PublishSingleFile for unpackaged configs; fix compile warnings

### PR DESCRIPTION
**Pull request by Scottj1s**

### CODE REVIEW

**Review by bpulliam — APPROVED** [review]

**Comment by Jay-o-Way** [comment]
@Scottj1s something tells me the following should be updated too. Am I right?
https://github.com/microsoft/WinUI-Gallery/blob/d664b7296605e15aae5d31b840a86bad0cd8f4fa/WinUIGallery/ItemPage.xaml.cs#L36

**Comment by Scottj1s** [comment]
> @Scottj1s something tells me the following should be updated too. Am I right?
> 

Thanks Jay!
https://github.com/microsoft/WinUI-Gallery/pull/1523/files

**Pull request merged**
